Explicit implicits
mlachkar/scala-migrat3 pull request #15
Opened 2020-10-26 22:10 UTC by mlachkar

2020-10-29 09:17 UTC, adpi2 reviewed
This looks very good!

I don't know why but `Incompat1` is not working on my machine. I got:
```
2020.10.29 10:14:40 [INFO] migrate.Main.previewMigration:29:16 - Migrating /home/piquerez/scalacenter/scala-migrat3/input/src/main/scala/Incompat1.scala
2020.10.29 10:14:40 [INFO] migrate.Main.buildMigrationFiles:92:41 - Found 0 patch candidate(s) in 1 file(s) after 176 milliseconds
[info] - Incompat1.scala *** FAILED ***
[info]   scalafix.interfaces.ScalafixException: Cannot apply patch on file /home/piquerez/scalacenter/scala-migrat3/input/src/main/scala/Incompat1.scala
[info]   at migrate.internal.FileMigrationState.$anonfun$previewAllPatches$2(FileMigrationState.scala:25)
[info]   at migrate.utils.ScalaExtensions$OptionExtension$.toTry$extension(ScalaExtensions.scala:35)
[info]   at migrate.internal.FileMigrationState.previewAllPatches(FileMigrationState.scala:25)
[info]   at migrate.internal.FileMigrationState.previewAllPatches$(FileMigrationState.scala:18)
[info]   at migrate.internal.FileMigrationState$Initial.previewAllPatches(FileMigrationState.scala:38)
[info]   at migrate.Main$.$anonfun$compileInScala3$1(Main.scala:62)
[info]   at scala.collection.immutable.List.map(List.scala:246)
[info]   at scala.collection.immutable.List.map(List.scala:79)
[info]   at migrate.Main$.compileInScala3(Main.scala:62)
[info]   at migrate.Main$.$anonfun$previewMigration$3(Main.scala:39)
```

2020-10-29 09:17 UTC, adpi2 commented on scalafix/rules/src/main/scala/migrate/ExplicitImplicitsRule.scala
> +      globalTree <- getTreeFromContext(context)
The same sequence of calls is made in the `MigrationRule` class. I suggest extracting that to a new method in `CompilerService`:

```scala
def getTreeFromContext(term: Term.Name)(implicit g: ScalafixGlobal): Option[g.Tree] =
  getContext.flatMap(getTreeFromContext)
```

2020-10-29 09:25 UTC, adpi2 commented
After a `reload; clean; migrate / test` everything is working fine!

2020-10-29 09:55 UTC, mlachkar commented on scalafix/rules/src/main/scala/migrate/ExplicitImplicitsRule.scala
> +      } else Patch.empty
yes. synthetics for conversions are always SYNTHETICS(OriginalTree). Not done yet

2020-10-29 09:56 UTC, mlachkar commented on scalafix/rules/src/main/scala/migrate/ExplicitImplicitsRule.scala
> +    }.toList.asPatch
ok

2020-10-30 15:06 UTC, adpi2 requested changes

2020-10-30 15:06 UTC, adpi2 commented on scalafix/rules/src/main/scala/migrate/ExplicitImplicitsRule.scala
> +      } else None
There is no default `case _ => None` and so there is a risk of failure?

2020-10-30 15:12 UTC, adpi2 approved these changes

2020-10-30 15:14 UTC, merged